# Loading necessary libraries
library(shiny)
library(shinydashboard)
library(leaflet)
library(plotly)
library(dplyr)
library(ggplot2)

# Read cleaned data file (dataset was cleaned using python)
netflix_userbase <- read.csv("cleaned_netflix_userbase.csv")

# Lookup table for country coordinates (these country coordinated were found using google)
country_coords <- data.frame(
  Country = c("United States", "Spain", "Canada", "United Kingdom", "Australia", "Germany", "France", "Brazil", "Mexico", "Italy"),
  Lat = c(37.09, 40.46, 56.13, 55.38, -25.27, 51.17, 46.23, -14.24, 23.63, 41.87),
  Lon = c(-95.71, -3.75, -106.35, -3.44, 133.78, 10.45, 2.21, -51.93, -102.55, 12.57)
)

# Merge country coordinates with the dataset
netflix_userbase <- netflix_userbase %>%
  left_join(country_coords, by = "Country")

# Define UI
ui <- dashboardPage(
  dashboardHeader(
    title = tags$div(
      style = "display: flex; align-items: center;",
      tags$span("Netflix Userbase", style = "font-size: 20px; font-weight: bold;")
    )
  ),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Global Subscriber Map", tabName = "map", icon = icon("globe")),
      menuItem("Revenue & Subscription", tabName = "revenue", icon = icon("dollar-sign")),
      menuItem("Device Usage Insights", tabName = "device", icon = icon("mobile-alt"))
    ),
    # Sidebar filters
    sliderInput("ageFilter", "Age Range", min = 18, max = 60, value = c(18, 60)),
    selectInput("genderFilter", "Gender", choices = c("All", "Male", "Female")),
    selectInput("countryFilter", "Country", choices = c("All", unique(netflix_userbase$Country))),
    selectInput("deviceFilter", "Device", choices = c("All", unique(netflix_userbase$Device)))
  ),
  dashboardBody(
    tabItems(
      # Global Subscriber Map Tab
      tabItem(
        tabName = "map",
        fluidRow(
          box(
            title = "Dataset Description",
            status = "info",
            solidHeader = TRUE,
            width = 12,
            div(
              style = "display: flex; align-items: center;",
              img(src = "netflix_icon.png", height = "60px", style = "margin-right: 20px;"),
              div(
                p("This dashboard provides insights into Netflix's userbase dataset, sourced from Kaggle, which includes information about 2500 subscribers across 10 countries:",
                  tags$b("United States, Spain, Canada, United Kingdom, Australia, Germany, France, Brazil, Mexico, and Italy.")),
                p("The dataset contains key variables such as:",
                  tags$ul(
                    tags$li("Subscription Type (Basic, Standard, Premium)"),
                    tags$li("Monthly Revenue"),
                    tags$li("Join Date and Last Payment Date"),
                    tags$li("Age"),
                    tags$li("Gender"),
                    tags$li("Device Usage (Laptop, Tablet, Smartphone, SmartTV)")
                  )
                ),
                p("All information about 1-month plan duration is included to analyze short-term subscription trends.")
              )
            )
          )
        ),
        
        ## data cards
        fluidRow(
          valueBoxOutput("totalSubscribers", width = 3),
          valueBoxOutput("avgRevenue", width = 3),
          valueBoxOutput("mostPopularPlan", width = 3),
          valueBoxOutput("topDevice", width = 3)
        ),
        
        ## Global map and density plot
        fluidRow(
          box(
            title = "Global Subscriber Map",
            status = "primary",
            solidHeader = TRUE,
            width = 6,
            leafletOutput("worldMap"),
            p("This map shows the distribution of Netflix subscribers across countries. Click on a country to see details like the number of subscribers, average age, and predominant subscription type.")
          ),
          box(
            title = "Age Distribution by Gender",
            status = "info",
            solidHeader = TRUE,
            width = 6,
            plotlyOutput("ageDensityPlot"),
            p("This density plot illustrates the age distribution of Netflix subscribers by gender. Use the filters to explore how age varies across different demographics.")
          )
        )
      ),
      # Revenue & Subscription Tab
      tabItem(
        tabName = "revenue",
        fluidRow(
          box(
            title = "Monthly Revenue by Subscription Type",
            status = "success",
            solidHeader = TRUE,
            plotlyOutput("revenuePlot"),
            p("This bar chart shows the total monthly revenue generated by each subscription type. It helps identify which subscription type contribute the most to Netflix's revenue.")
          ),
          box(
            title = "Subscription Trends Over Time",
            status = "warning",
            solidHeader = TRUE,
            plotlyOutput("subscriptionTrendPlot"),
            p("This line chart tracks the number of new subscriptions over time. It helps identify seasonal patterns or trends in customer acquisition.")
          )
        )
      ),
      # Device Usage Tab
      tabItem(
        tabName = "device",
        fluidRow(
          box(
            title = "Device Usage Distribution",
            status = "info",
            solidHeader = TRUE,
            plotlyOutput("devicePlot"),
            p("This pie chart shows the proportion of users on different devices.")
          ),
          box(
            title = "Revenue by Device",
            status = "success",
            solidHeader = TRUE,
            plotlyOutput("deviceRevenuePlot"),
            p("This bar chart compares the total revenue generated by users on different devices. It helps identify which devices contribute the most to Netflix's revenue.")
          )
        )
      )
    )
  )
)

# Server
server <- function(input, output) {
  
  # Reactive data for filters
  filteredData <- reactive({
    data <- netflix_userbase %>%
      filter(Age >= input$ageFilter[1] & Age <= input$ageFilter[2])
    
    if (input$genderFilter != "All") {
      data <- data %>% filter(Gender == input$genderFilter)
    }
    
    if (input$countryFilter != "All") {
      data <- data %>% filter(Country == input$countryFilter)
    }
    
    if (input$deviceFilter != "All") {
      data <- data %>% filter(Device == input$deviceFilter)
    }
    
    data
  })
  
  ## Data cards
  # Total Subscribers
  output$totalSubscribers <- renderValueBox({
    total_subs <- nrow(filteredData())
    valueBox(
      total_subs, "Total Subscribers", icon = icon("users"),
      color = "red"
    )
  })
  
  # Average Monthly Revenue
  output$avgRevenue <- renderValueBox({
    avg_revenue <- round(mean(filteredData()$Monthly.Revenue, na.rm = TRUE), 2)
    valueBox(
      paste0("$", avg_revenue), "Avg Monthly Revenue", icon = icon("dollar-sign"),
      color = "green"
    )
  })
  
  # Most Popular Subscription Type
  output$mostPopularPlan <- renderValueBox({
    popular_plan <- filteredData() %>%
      count(Subscription.Type, sort = TRUE) %>%
      top_n(1) %>%
      pull(Subscription.Type)
    valueBox(
      popular_plan, "Most Popular Plan", icon = icon("fire"),
      color = "orange"
    )
  })
  
  # Most Used Device
  output$topDevice <- renderValueBox({
    top_device <- filteredData() %>%
      count(Device, sort = TRUE) %>%
      top_n(1) %>%
      pull(Device)
    valueBox(
      top_device, "Top Device Used", icon = icon("mobile-alt"),
      color = "blue"
    )
  })
  
  ## Global Subscriber Map
  output$worldMap <- renderLeaflet({
    data <- filteredData() %>%
      group_by(Country, Lat, Lon) %>%
      summarise(
        Subscribers = n(),
        AvgAge = mean(Age),
        PredominantSubscription = names(sort(table(`Subscription.Type`), decreasing = TRUE))[1]
      )
    
    leaflet(data) %>%
      addTiles() %>%
      addCircleMarkers(
        lng = ~Lon, lat = ~Lat, radius = ~Subscribers / 10,
        popup = ~paste("Country: ", Country, "<br>",
                       "Subscribers: ", Subscribers, "<br>",
                       "Avg Age: ", round(AvgAge, 1), "<br>",
                       "Predominant Subscription: ", PredominantSubscription)
      )
  })
  
  ## Age Distribution by Gender-Density Plot
  output$ageDensityPlot <- renderPlotly({
    data <- filteredData()
    
    # Creating a density plot using ggplot2
    p <- ggplot(data, aes(x = Age, fill = Gender)) +
      geom_density(alpha = 0.5) +
      scale_fill_manual(values = c("Male" = "blue", "Female" = "pink")) +
      labs(title = "Age Distribution by Gender",
           x = "Age",
           y = "Density") +
      theme_minimal()
    
    # Converts ggplot to interactive Plotly plots
    ggplotly(p)
  })
  
  ## Revenue by Subscription Type
  output$revenuePlot <- renderPlotly({
    data <- filteredData() %>%
      group_by(`Subscription.Type`) %>%
      summarise(TotalRevenue = sum(`Monthly.Revenue`))
    
    plot_ly(data, x = ~`Subscription.Type`, y = ~TotalRevenue, type = "bar", 
            color = ~`Subscription.Type`, colors = "Set1") %>%
      layout(title = "Total Monthly Revenue by Subscription Type",
             xaxis = list(title = "Subscription Type"),
             yaxis = list(title = "Total Revenue ($)"))
  })
  
  ## Subscription Trends Over Time
  output$subscriptionTrendPlot <- renderPlotly({
    data <- filteredData() %>%
      mutate(`Join.Date` = as.Date(`Join.Date`, format = "%Y %b %d")) %>%  # Convert to Date format
      group_by(JoinDate = `Join.Date`) %>%  # Group by Join Date
      summarise(Subscribers = n())  # Count subscribers for each date
    
    # Create a line chart
    plot_ly(data, x = ~JoinDate, y = ~Subscribers, type = "scatter", mode = "lines") %>%
      layout(title = "Subscription Trends Over Time",
             xaxis = list(title = "Join Date"),
             yaxis = list(title = "Number of Subscribers"))
  })
  
  ## Device Usage Distribution
  output$devicePlot <- renderPlotly({
    data <- filteredData() %>%
      group_by(Device) %>%
      summarise(Count = n())
    
    plot_ly(data, labels = ~Device, values = ~Count, type = "pie") %>%
      layout(title = "Device Usage Distribution")
  })
  
  ## Revenue by Device
  output$deviceRevenuePlot <- renderPlotly({
    data <- filteredData() %>%
      group_by(Device) %>%
      summarise(TotalRevenue = sum(`Monthly.Revenue`))
    
    plot_ly(data, x = ~Device, y = ~TotalRevenue, type = "bar", 
            color = ~Device, colors = "Set2") %>%
      layout(title = "Revenue by Device",
             xaxis = list(title = "Device"),
             yaxis = list(title = "Total Revenue ($)"))
  })
}

# Run the Shiny App
shinyApp(ui, server)